### ISSUE TITLE
Zephyr RTOS

### ISSUE THREAD

**Issue by praveen-petal** [antshiv/ThrustStand#2]
Hai Sir,
     How to learn Zephyr RTOS from the beginning for nRF9160 DK ? If you have any tutorial regards Zephyr RTOS, please share the document or link. 

Regards,
Praveen M

**Comment by antshiv** [comment]
This is unrelated to this repo but to answer your question try learning from Nordic Semis tutorials - https://www.nordicsemi.com/Support/Nordic-Developer-Academy
